import React, { useEffect } from "react";
import Head from 'next/head'
import { useRouter } from 'next/router'
import { Provider } from 'wagmi'
import { Box } from "@chakra-ui/react";
import LandingSection from '../components/Sections/LandingSection';
import NavBar from '../components/NavBar';
import connectors from '../utils/connectors'
import { useAccount } from 'wagmi';

export default function Home() {
  const [{ data: accountData }] = useAccount();
  const router = useRouter();
  useEffect(() => {
    console.log('accountData from index:', accountData);
    if (accountData) {
      router.push('/dashboard');
    }
  }, [accountData])
  return (
    <Provider autoConnect connectors={connectors}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box bg='black'>
        <NavBar />
        <LandingSection accountData={accountData} />
      </Box>
    </Provider>
  )
}
